### ISSUE TITLE
can't use by 13.6.4 (22G513)

### ISSUE THREAD

**Issue by cooker** [barseghyanartur/app-menu#19]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/b8c86866-40fb-4f66-af4b-de86f3976b03">

**Comment by barseghyanartur** [comment]
Thanks for reporting. 

I've written this on Sanoma, which is 14.x anyway. 

It's probably a compillation/backwards compatibility issue that can be solved. 

I'll investigate and let you know.

**Comment by barseghyanartur** [comment]
Yep, `MACOSX_DEPLOYMENT_TARGET` is set to 14.1. I'll see if I can change it to 13.0 (or whatever makes sense).

**Comment by barseghyanartur** [comment]
@cooker: 

Solved in 0.1.5. Please, try again.
